[project]
name = "mlx-work"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "stonedev-app", email = "54230974+stonedev-app@users.noreply.github.com" }
]
requires-python = ">=3.12"
dependencies = [
    "mlx-lm>=0.31.3",
]

[project.scripts]
mlx-work = "mlx_work:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
